src/gpi/urls.py
from django.contrib import admin
from django.urls import path, include
from gpi_core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gpi_core.urls')),
]

src/gpi_core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),

    # Routes GPI
    path("gpi/create", views.create_gpi, name="create_gpi"),
    path("gpi/view/<int:gpi_id>", views.view_gpi, name="view_gpi"),

    # Routes Agence
    path("agency/create/", views.create_agency, name="create_agency"),

    # Routes Dashboard
    path("dashboard/", views.home, name="gpi_list"),
    path("dashboard/sorted/<str:criteria>/<str:order>/", views.sort_gpi, name="sort"),
    path("dashboard/search_<str:string_searched>/", views.search_gpi, name="search"),
    path("dashboard/get_all_gpi/", views.get_all_gpi, name="get_all_gpi"),

    # Routes Tâches
    path("task/update/gpi_<int:gpi_id>/task_<int:task_id>", views.view_task, name="view_task"),
    path("task/create/gpi_<int:gpi_id>", views.view_task, name="create_task"),
    path("task/delete/gpi_<int:gpi_id>/task_<int:task_id>", views.delete_task, name="delete_task"),

    # Routes Commentaires
    path("comment/create/task_<int:task_id>", views.create_comment, name="create_comment"),
    path("comment/update/task_<int:task_id>/comment_<int:comment_id>", views.update_comment, name="update_comment"),
    path("comment/delete/task_<int:task_id>/comment_<int:comment_id>", views.delete_comment, name="delete_comment"),

]

src/gpi_core/models.py
import datetime

from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import timedelta
from q1c1_django_utils import validators
from jours_feries_france import JoursFeries


class Agency(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=250)
    metropolis = models.CharField(max_length=100)
    acquisition_date = models.DateField('date Acquisition agence')
    validator_zip_code = validators.ZipCodeValidator()
    zip_code = models.CharField(null=True, max_length=5, validators=[validator_zip_code])

    def __str__(self):
        return f'{self.name}'


class GPI(models.Model):
    STATUS_OPEN = 'OPEN'
    STATUS_CLOSED = 'CLOSED'
    STATUS_NOT_STARTED = 'NOT_STARTED'
    STATUSES = (
        (STATUS_OPEN, _('Ouvert')),
        (STATUS_CLOSED, _('Fermé')),
        (STATUS_NOT_STARTED, _('Non commencé'))
    )

    protocol_signing_date = models.DateField('date de signature du protocole')
    definitive_signing_date = models.DateField('date de signature définitive')
    agency = models.OneToOneField(Agency, on_delete=models.CASCADE)
    earliest_start_date = models.DateField('date de début au plus tôt', null=True)
    latest_start_date = models.DateField('date de début au plus tard', null=True)
    earliest_end_date = models.DateField('date de fin au plus tôt', null=True)
    latest_end_date = models.DateField('date de fin au plus tard', null=True)
    status = models.TextField(choices=STATUSES)

    def compute_margins(self):
        """
        Calcul global des marges des tâches du GPI
        """
        list_first_tasks = self.tasks.filter(come_before__isnull=True)
        for task in list_first_tasks:
            task.recursive_margin_routine()

    def compute_latest_dates(self):
        """
        Calcul global des dates de début et de fin au plus tard des tâches du GPI
        """
        list_last_tasks = self.tasks.filter(come_after__isnull=True)
        if len(list_last_tasks) > 0:
            latest_end_date = max([t.earliest_end_date for t in list_last_tasks])
        for task in list_last_tasks:
            task.latest_end_date = latest_end_date
            task.recursive_latest_dates_routine()

    def compute_earliest_dates(self):
        """
        Calcul global des dates de début et de fin au plus tôt des tâches du GPI
        """
        list_first_tasks = self.tasks.filter(come_before__isnull=True)
        for task in list_first_tasks:
            task.recursive_earliest_dates_routine()

    def compute_h_ranks(self):  # h rank? depth/profondeur plutôt
        """

        Returns:

        """
        dict_h_ranks = {}
        # regarder prefetch pour loader les many foreignkeys
        cached_queryset = self.tasks.filter(come_before__isnull=True)
        for task in cached_queryset:
            task.recursive_rank_h_routine(dict_h_ranks=dict_h_ranks, cached_queryset=task)
        return dict_h_ranks

    def compute_v_ranks(self):
        """
        Calcul des positionnements verticaux des tâches selon leur nombre de successeurs
        cette méthode s'appuie sur une méthode définie dans la classe Task pour calculer les
        rangs et les hauteurs récursivement à partir des tâches enfants

        Returns :
        computed_tasks : un dictionnaire contenant les hauteurs des tâches
        """
        all_tasks = self.tasks.all()
        dict_visited_tasks = {task: [False, 0] for task in all_tasks}
        list_first_tasks = self.tasks.filter(come_before__isnull=True)
        if len(all_tasks) > 0:
            for first_task in list_first_tasks:
                first_task.height = first_task.rank_v = max([t.rank_v + 1 for t in list_first_tasks])
                first_task.recursive_rank_v_descent(tasks_explored=dict_visited_tasks, calling_task=first_task)
                dict_visited_tasks[first_task][1] = first_task.height
        return dict_visited_tasks


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Task(models.Model):
    STATUS_BLOCKED = 'BLOCKED'
    STATUS_WAITING = 'UNINITIATED'
    STATUS_IN_PROGRESS = 'ONGOING'
    STATUS_FINISHED = 'FINISHED'
    STATUSES = (
        (STATUS_BLOCKED, _('Bloquée')),
        (STATUS_WAITING, _('En attente')),
        (STATUS_IN_PROGRESS, _('En cours')),
        (STATUS_FINISHED, _('Terminée')),
    )

    description = models.CharField(max_length=250, null=True)
    name = models.CharField(max_length=50, null=False)
    real_end_date = models.DateField(null=True, blank=True)
    real_start_date = models.DateField(null=True, blank=True)
    earliest_start_date = models.DateField(null=True, blank=True)
    latest_start_date = models.DateField(null=True, blank=True)
    earliest_end_date = models.DateField(null=True, blank=True)
    latest_end_date = models.DateField(null=True, blank=True)
    come_before = models.ManyToManyField(to='self', symmetrical=False, related_name="come_after", blank=True)
    duration = models.DurationField(null=False)
    margin = models.DurationField(null=True)
    author = models.ForeignKey(null=True, to='InternalContributor', on_delete=models.CASCADE)
    category = models.ForeignKey(null=False, to='Category', on_delete=models.CASCADE)
    gpi = models.ForeignKey(null=False, to='GPI', on_delete=models.CASCADE, related_name='tasks')
    status = models.TextField(choices=STATUSES)

    def __init__(self, *args, **kwargs):
        super(Task, self).__init__(*args, **kwargs)
        self.rank_v = 0
        self.height = None
        self.rank_h = 0

    def __str__(self):
        return self.name

    def recursive_rank_v_descent(self, tasks_explored: dict, calling_task: "Task" = None):
        """Calcul des rangs et des hauteurs de chaque tâche pour pouvoir les positionner verticalement.

        Args :
            tasks_explored :
            calling_task :

        Returns:

        """
        suc_list = self.come_after.all()
        explored_suc = 0
        if calling_task is not None and self.height is None:
            self.height = calling_task.rank_v
        else:
            if self.height is None:
                self.height = 0
        tasks_explored[self][1] = self.height
        for suc in suc_list:
            if tasks_explored[suc][0] is True:
                explored_suc += 1
        if explored_suc == len(suc_list):  # si tous les sommets fils ont été explorés, alors, le sommet actuel est considéré comme exploré
            tasks_explored[self][0] = True
        if len(suc_list) == 0:  # si pas de successeurs, on met à jour notre rang et on le retourne incrémenté
            self.rank_v = calling_task.rank_v
            return self.rank_v + 1
        elif len(suc_list) > 0 and not tasks_explored[self][0]: # si présence de successeurs, on met à jour notre rang grâce au retour de l'appel récursif sur chacun des successeurs
            self.rank_v = calling_task.rank_v
            for suc in suc_list:
                self.rank_v = suc.recursive_rank_v_descent(tasks_explored=tasks_explored, calling_task=self)
            tasks_explored[self][0] = True
            tasks_explored[self][1] = self.height
            return self.rank_v + 1 # retour à l'appelant de la valeur du rang + 1 après avoir exploré tous les successeurs et mis à jour notre rang
        return self.rank_v + 1

    def recursive_margin_routine(self):
        """Routine de calcul récursif des marges disponibles sur une tâche,
        On fait la différence de dates entre la date de début au plus tard et la date de début au plus tôt.
        On devrait retrouver la même valeur en faisant la différence entre la date de fin au plus tard et la date de fin
        au plus tôt. Cette marge est enregistrée dans l'attribut margin. Il faut au préalable que les dates de début/fin
        au plus tôt/tard aient été calculées
        """
        suc_list = self.come_after.all()
        self.margin = self.latest_start_date - self.earliest_start_date
        self.save()
        for suc in suc_list:
            suc.recursive_margin_routine()

    def recursive_earliest_dates_routine(self):
        """Routine de calcul récursif des dates au plus tôt des tâches,
        on récupère la tâche dont la somme de la date de début au plus tôt et de la durée est maximale
        puis on boucle à partir de la durée de la tâche en jours en sautant les indices de jours qui sont compris dans
        les week-ends ou les jours fériés, on applique une procédure similaire pour la date de fin au plus tôt de la
        tâche
        correction manuelle, une tâche ne doit pas pouvoir se commencer sur un week-end ou un jour férié
        """
        pred_list = self.come_before.all()
        suc_list = self.come_after.all()
        one_day = timedelta(days=1)
        if len(pred_list) > 0:
            longest_pred_end_date = max(pred.earliest_end_date for pred in pred_list)
            longest_pred_end_date += one_day
            while longest_pred_end_date.isoweekday() > 5:
                longest_pred_end_date += one_day
            self.earliest_start_date = longest_pred_end_date

        days_index = 0
        loop_date = self.earliest_start_date
        while days_index < self.duration.days - 1:   # tant que l'on n'a pas ajouté tous les jours de durée
            # si rajouter un jour travaillé ne nous fait pas tomber sur le week-end, on le compte
            if (loop_date + one_day).isoweekday() < 6:
                days_index += 1
            loop_date += one_day
        self.earliest_end_date = loop_date
        self.save()
        for successor in suc_list:
            successor.recursive_earliest_dates_routine()

    def recursive_latest_dates_routine(self):
        """ Routine de calcul des dates au plus tard des tâches,
        si pas de successeurs, on récupère la date de fin au plus tôt avec une valeur maximale

src/gpi_core/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from gpi_core.models import *
from gpi_core.forms import GPIForm, AgencyForm, TaskForm, CommentForm
from django.core.exceptions import PermissionDenied

# Create your views here.


def home(request):
    list_gpi = GPI.objects.all()
    return render(request, 'gpi_core/list_gpi.html', {'list_gpi': list_gpi})


def sort_gpi(request, criteria: str, order: str):
    criteria = criteria.split("_link")[0]
    if criteria in ['name', 'metropolis', 'address', 'zip_code']:
        criteria = 'agency__' + criteria
    if order == 'desc':
        criteria = "-"+criteria
    gpi_set = GPI.objects.order_by(criteria)
    # appel d'une vue dans une vue + nom des variables et nom de la fonction
    gpi_dict = get_all_fields_as_list(gpi_set)
    return JsonResponse({"gpi_sorted": list(gpi_dict)})


def create_gpi(request):
    form = GPIForm()
    if request.method == 'POST':
        form = GPIForm(request.POST)
        if form.is_valid():
            form.save()
    #         il doit y avoir un moyen de set 'gpi_core' comme url par défaut de l'application
    # on peut utiliser locals()
    return render(request, 'gpi_core/create_gpi.html', {'form': form})


def create_agency(request):
    form = AgencyForm()
    if request.method == 'POST':
        form = AgencyForm(request.POST)
        if form.is_valid():
            form.save()
    return render(request, 'gpi_core/create_agency.html', {'form': form})


def search_gpi(request, string_searched: str):
    matching_gpi_set = GPI.objects.filter(agency__name__icontains=string_searched)
    matching_gpi_dict = get_all_fields_as_list(matching_gpi_set)
    return JsonResponse({"gpi_found": list(matching_gpi_dict)})


def get_all_gpi(request):
    gpi_set = GPI.objects.all()
    gpi_dict = get_all_fields_as_list(gpi_set)
    return JsonResponse({"all_gpi": list(gpi_dict)})


def view_gpi(request, gpi_id):
    gpi = GPI.objects.get(id=gpi_id)
    if request.method == 'GET':
        computed_tasks = gpi.compute_v_ranks()
    return render(request, 'gpi_core/view_gpi.html', {'gpi': gpi,
                                                      'computed_tasks': computed_tasks,
                                                      'categories': Category.objects.all()
                                                      })


def view_task(request, gpi_id, task_id=None):
    template = "gpi_core/view_task.html"
    task = None
    context = {}
    gpi = GPI.objects.get(pk=gpi_id)
    comment_form = CommentForm()
    if task_id is not None:
        task = Task.objects.get(pk=task_id)
    else:
        if request.method == "GET":
            form = TaskForm(gpi)
        else:
            form = TaskForm(gpi, request.POST)
    if task is not None:
        if request.method == "GET":
            form = TaskForm(gpi=gpi, instance=task)
            form.initial["duration"] = task.duration.days
        else:
            form = TaskForm(gpi, request.POST, instance=task)
        context.update({"task": task})
    context.update({"task_creation_form": form,
                    "comment_form": comment_form,
                    "gpi": gpi})

    if request.method == "GET":
        if task is not None and task in form.fields["come_after"].queryset and task in form.fields["come_before"].queryset:
            form.fields["come_before"].queryset = gpi.tasks.exclude(pk=task.id)
            form.fields["come_after"].queryset = gpi.tasks.exclude(pk=task.id)
        return render(request, template_name=template, context=context)
    if form.is_valid():
        form.save()
        gpi.compute_earliest_dates()
        gpi.compute_latest_dates()
        gpi.compute_margins()
        gpi.compute_v_ranks()
    return render(request, template_name=template, context=context)


def create_comment(request, task_id):
    task = Task.objects.get(pk=task_id)
    author = InternalContributor.objects.first()  # TODO: relier à l'utilisateur actuellement connecté
    if task is not None:
        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment_form.save()
                return render(request=request, template_name="gpi_core/view_task.html")


def delete_comment(request, task_id, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    task = Task.objects.get(pk=task_id)
    task_creation_form = TaskForm(instance=task)
    comment_form = CommentForm(request)
    context = {"task": task, "task_creation_form": task_creation_form, "comment_form": comment_form}
    if comment.task == task:
        comment.delete()
        return render(request, template_name="gpi_core/view_task.html", context=context)
    else:
        raise PermissionDenied


def update_comment(request, task_id, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    task = Task.objects.get(pk=task_id)
    if comment.task == task:
        comment_form = CommentForm(request, instance=comment)
        if comment_form.is_valid():
            comment_form.save()
            return render(request, template_name="gpi_core/view_task.html")


def delete_task(request, gpi_id, task_id):

    gpi = GPI.objects.get(pk=gpi_id)
    task = Task.objects.get(pk=task_id)

    if task is not None and task.gpi.id == gpi.id:
        task.delete()
        gpi.compute_earliest_dates()
        gpi.compute_latest_dates()
        gpi.compute_margins()
    return redirect('view_gpi', gpi_id=task.gpi.id)


def get_all_fields_as_list(gpi_set):
    # gpi_dict = une liste,
    # parcours de liste par list[index] plutôt que par élément,
    # c'est de la serialisation? Si oui, utiliser from django.core import serializers ou obj.__dict__
    gpi_dict = list(gpi_set.values("id", "definitive_signing_date", "protocol_signing_date", "status"))
    for gpi_counter in range(len(gpi_dict)):
        gpi_dict[gpi_counter]["agency_name"] = gpi_set[gpi_counter].agency.name
        gpi_dict[gpi_counter]["agency_address"] = gpi_set[gpi_counter].agency.address
        gpi_dict[gpi_counter]["agency_zip_code"] = gpi_set[gpi_counter].agency.zip_code
        gpi_dict[gpi_counter]["agency_metropolis"] = gpi_set[gpi_counter].agency.metropolis
    return gpi_dict

src/gpi_core/templates/gpi_core/base.html
<!DOCTYPE html>
<html lang="fr-FR">
<head>
    <meta charset="UTF-8">
    <title>Web GPI</title>
    {% block ressources %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>

src/gpi_core/templates/gpi_core/create_agency.html
{% extends 'gpi_core/base.html' %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit"/>
</form>
    <a href="{% url 'home' %}">Accueil</a>

{% endblock %}

src/gpi_core/templates/gpi_core/create_gpi.html
{% extends 'gpi_core/base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit">
    </form>
    <a href="{% url 'home' %}">Accueil</a>
{% endblock %}

src/gpi_core/templates/gpi_core/view_gpi.html
{% extends 'gpi_core/base.html' %}
{% block ressources %}
    <link rel="stylesheet" href="/static/view_gpi.css" type="text/css">
    <script src="/static/view_gpi.js" type="application/javascript" defer></script>
{% endblock %}
{% block content %}
    <div class="calendar-container">
        <div class="tasks-container"></div>
    </div>
    <template id="column">
    <div class="column-wrapper">
    </div>
    </template>
    <template id="day">
        <div class="day-container">
            <span class="day-cell"></span>
        </div>
    </template>
    <template id="month">
        <div class="month-container">
            <span class="month-cell"></span>
        </div>
    </template>
    <template id="year">
        <div class="year-container">
            <span class="year-cell"></span>
        </div>
    </template>
    {{ task_creation_form.errors }}
    <a href="{% url 'create_task' gpi.id  %}"><button id="add_task_button">Ajout tâche</button></a>
    <a href="{% url "gpi_list" %}"><button> Retour à l'accueil</button></a>
    {% for task, height in computed_tasks.items %}
        <div class="task"
             id="task_{{ task.id }}"
             data-earliest-start-date="{{ task.earliest_start_date|date:'Y/m/d' }}"
             data-earliest-end-date="{{ task.earliest_end_date|date:'Y/m/d' }}"
             data-margin="{{ task.margin }}"
             data-duration="{{ task.duration.days }}"
                {% if task.come_before.all %}
                    data-pred-list="{% for pred in task.come_before.all %}{{ pred.id }}{% if not forloop.last %}-{% endif %}{% endfor %}"
                {% endif %}
             data-height="{{ height.1 }}"
        >
            <a href="{% url "view_task" gpi.id task.id %}">
        {{ task.name }}
        </a>
        </div>
    {% endfor %}
    <div class="categories-container">{% for category in categories %}<span class="category-button">{{ category.name }}</span>{% endfor %}</div>
{% endblock %}

src/gpi_core/templates/gpi_core/view_task.html
{% extends 'gpi_core/base.html' %}
{% block ressources %}
    <link rel="stylesheet" href="/static/view_task.css" type="text/css">
    <script src="/static/view_task.js" type="application/javascript" defer></script>
{% endblock %}
{% block content %}
    <form action="" method="post" id="task-form">
        {% csrf_token %}
        <table>
            <div class="row">{{ task_creation_form.name.label_tag }} {{ task_creation_form.name }}</div>
            <div class="row">{{ task_creation_form.description.label_tag }} {{ task_creation_form.description }}</div>
            <div class="row">{{ task_creation_form.duration.label_tag }} {{ task_creation_form.duration }}</div>
        <div class="row">


            {% if task_creation_form.come_after|length > 0 %}
                <div id="id_come_after" class="widget">
                    <span class="label-list">{{ task_creation_form.come_after.label_tag }}</span>
                    <span class="search-field"><input type="text"></span>
                    <div class="choices-container">
                        {% for task_come_after in task_creation_form.come_after %}
                            <div class="choice" data-task-id="{{ task_come_after.data.value.instance.id }}"
                                 data-pred-list="{% for pred in task_come_after.data.value.instance.come_before.all %}{{ pred.id }}{% if not forloop.last %}-{% endif %}{% endfor %}"
                                 data-suc-list="{% for suc in  task_come_after.data.value.instance.come_after.all %}{{ suc.id }}{% if not forloop.last %}-{% endif %}{% endfor %}">
                                {{ task_come_after }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            {% if task_creation_form.come_before|length > 0 %}
                <div id="id_come_before" class="widget">
                    <span class="label-list">{{ task_creation_form.come_before.label_tag }}</span>
                    <span class="search-field"><input type="text"></span>
                    <div class="choices-container">
                        {% for task_come_before in  task_creation_form.come_before %}
                            <div class="choice" data-task-id="{{ task_come_before.data.value.instance.id }}"
                                 data-pred-list="{% for pred in task_come_before.data.value.instance.come_before.all %}{{ pred.id }}{% if not forloop.last %}-{% endif %}{% endfor %}"
                                 data-suc-list="{% for suc in task_come_before.data.value.instance.come_after.all %}{{ suc.id }}{% if not forloop.last %}-{% endif %}{% endfor %}">
                                {{ task_come_before }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        </div>
            <div class="row">
                {{ task_creation_form.earliest_start_date.label_tag }}
                {{ task_creation_form.earliest_start_date }} {{ task_creation_form.earliest_start_date.field.type }}
            </div>
            <div class="row">{{ task_creation_form.category.label_tag }} {{ task_creation_form.category }}</div>
            <div class="row">{{ task_creation_form.status.label_tag }}{{ task_creation_form.status }}</div>
        </table>
    </form>
    {% if task %}
    <form method="post" action="{% url "create_comment" task.id %}">
    {{ comment_form }}
    <input type="submit" value="ajouter commentaire">
    {% endif %}
    </form>
    <button type="submit" form="task-form">{% if not task %}créer{% else %}Modifier{% endif %}</button>
    {% if task %}<a href="{% url "delete_task" gpi.id task.id %}">
        <button>supprimer</button>
    </a>{% endif %}
    <a href="{% url "view_gpi" gpi.id %}">Retour au GPI</a>
    <a href="{% url "gpi_list" %}">Retour à la vue globale</a>
{% endblock %}